name: M2 Coding Standard
on:
  push:
  pull_request:
    branches:
      - "*"
jobs:
  static:
    name: Magento 2 Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: M2 code standard
        id: magento
        uses: aNereds/magento2-coding-standard@1.0.0
        with:
          fileExtensions: "php,phtml,xml"
          onlyErrors: "no"
          sourceReport: "yes"
      - name: Get the output time
        run: echo "Action Output, ${{ steps.magento.outputs.time }}"
